


CREATE TABLE IF NOT EXISTS DEPARTMENTS(
    ID          BIGINT          AUTO_INCREMENT      PRIMARY KEY, 
    `NAME`      VARCHAR(255)                        NULL
);


CREATE TABLE IF NOT EXISTS EMPLOYEES(
    ID                  BIGINT          AUTO_INCREMENT      PRIMARY KEY,
    `NAME`              VARCHAR(255)    NULL,
    DEPARTMENT_ID       BIGINT          ,
    CONSTRAINT fk_c_department FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)       
);


CREATE TABLE IF NOT EXISTS COURSES(
    ID                      BIGINT              AUTO_INCREMENT      PRIMARY KEY,
    `NAME`                  VARCHAR(255)    ,
    STARTS                  DATE            ,
    DURATION_IN_MONTHS      FLOAT           ,

    CONSTRAINT fk_c_employee FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)          
);


CREATE TABLE IF NOT EXISTS PROJECTS(
    ID                      BIGINT          AUTO_INCREMENT    PRIMARY KEY,
    `NAME`                  VARCHAR(255)               
);


CREATE TABLE IF NOT EXISTS EMPLOYEES_PROJECTS(
    EMPLOYEE_ID             BIGINT,
    PROJECT_ID              BIGINT,

    PRIMARY KEY(EMPLOYEE_ID, PROJECT_ID),
    CONSTRAINT fk_ep_employee FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    CONSTRAINT fk_ep_projects FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);